# Generated by Django 3.1.7 on 2021-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
    ]
