# Generated by Django 3.1.7 on 2021-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20210408_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
