# Generated by Django 3.1.7 on 2021-04-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['name']},
        ),
    ]
