# Generated by Django 3.1.7 on 2021-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20210408_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
