# Generated by Django 3.1.7 on 2021-04-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20210417_1335'),
        ('seller', '0013_auto_20210417_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='agent',
        ),
        migrations.AddField(
            model_name='seller',
            name='agent',
            field=models.ManyToManyField(related_name='agent', to='agent.Agent'),
        ),
    ]
