# Generated by Django 3.1.7 on 2021-04-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_auto_20210421_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='agent',
        ),
    ]
