# Generated by Django 3.1.7 on 2021-04-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_agent_seller'),
        ('seller', '0015_remove_seller_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agent.agent'),
        ),
    ]
