# Generated by Django 3.1.7 on 2021-04-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
    ]
