# Generated by Django 3.1.7 on 2021-04-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
