# Generated by Django 3.1.7 on 2021-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_remove_seller_agent'),
        ('agent', '0002_auto_20210417_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='seller',
            field=models.ManyToManyField(related_name='seller', to='seller.Seller'),
        ),
    ]
