# Generated by Django 3.1.7 on 2021-04-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='seller',
        ),
    ]
