# Generated by Django 3.1.7 on 2021-04-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_orderitem_product'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='seller.seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='sellers',
            field=models.ManyToManyField(related_name='sellers', to='seller.Seller'),
        ),
    ]
