# Generated by Django 3.1.7 on 2021-04-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20210408_2201'),
        ('order', '0003_auto_20210408_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sellers',
            field=models.ManyToManyField(related_name='orders', to='seller.Seller'),
        ),
    ]
