# Generated by Django 3.1.7 on 2021-04-13 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_auto_20210414_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
