# Generated by Django 3.1.7 on 2021-04-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210414_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
    ]
