# Generated by Django 3.1.7 on 2021-04-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('order', '0014_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agents',
            field=models.ManyToManyField(related_name='orders', to='agent.Agent'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agent.agent'),
        ),
    ]
