# Generated by Django 3.1.7 on 2021-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210416_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
