# Generated by Django 3.1.7 on 2021-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_is_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refunde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_replaced',
            field=models.BooleanField(default=False),
        ),
    ]
