# Generated by Django 3.1.7 on 2021-04-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210418_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_refunde',
            new_name='is_refunded',
        ),
    ]
