# Generated by Django 3.1.7 on 2021-04-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20210420_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='agent',
        ),
    ]
