# Generated by Django 3.1.7 on 2021-04-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_agent_seller'),
        ('order', '0020_auto_20210421_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_refunded',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_replaced',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='agents',
            field=models.ManyToManyField(related_name='orders', to='agent.Agent'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agent.agent'),
        ),
    ]
