# Generated by Django 3.1.7 on 2021-04-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20210422_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
